details:
  namespace: student29-bookinfo-prd
  image: ghcr.io/newbeerpongsakorn/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.opsta.net
  path: "/student29/details(/|$)(.*)"
  serviceType: ClusterIP